// from https://github.com/luciascarlet/tailwind-moon-vscode/blob/main/themes/tailwind-moon-blue.json
module.exports = {
  name: "Tailwind Moon Blue",
  type: "dark",
  colors: {
    strings: "#7dd3fc",
    focusBorder: "#A78BFA",
    foreground: "#E2E8F0",
    "widget.shadow": "#0F172A",
    "selection.background": "#475569",
    errorForeground: "#e53e3e",
    "button.background": "#319795C0",
    "button.foreground": "#ffffff",
    "button.hoverBackground": "#319795",
    "dropdown.background": "#334155",
    "dropdown.border": "#475569",
    "dropdown.foreground": "#E2E8F0",
    "icon.foreground": "#94A3B8",
    "input.background": "#1E293B",
    "input.border": "#0F172A",
    "input.foreground": "#E2E8F0",
    "input.placeholderForeground": "#64748B",
    "inputOption.activeBorder": "#A78BFA",
    "inputValidation.errorBackground": "#334155",
    "inputValidation.errorBorder": "#e53e3e",
    "inputValidation.infoBackground": "#334155",
    "inputValidation.infoBorder": "#319795",
    "inputValidation.warningBackground": "#334155",
    "inputValidation.warningBorder": "#D69E2E",
    "scrollbar.shadow": "#000000A0",
    "scrollbarSlider.activeBackground": "#4a55687f",
    "scrollbarSlider.background": "#a0aec07f",
    "scrollbarSlider.hoverBackground": "#7180967f",
    "badge.foreground": "#334155",
    "badge.background": "#A78BFA",
    "progressBar.background": "#34D399",
    "list.activeSelectionBackground": "#475569",
    "list.activeSelectionForeground": "#F1F5F9",
    "list.dropBackground": "#a0aec0",
    "list.focusBackground": "#a0aec0",
    "list.highlightForeground": "#A78BFA",
    "list.hoverBackground": "#334155",
    "list.inactiveSelectionBackground": "#1E293B",
    "list.inactiveSelectionForeground": "#F1F5F9",
    "list.hoverForeground": "#F1F5F9",
    "list.focusForeground": "#E2E8F0",
    "list.invalidItemForeground": "#e53e3e",
    "list.errorForeground": "#e53e3e",
    "list.warningForeground": "#D69E2E",
    "listFilterWidget.background": "#334155",
    "listFilterWidget.outline": "#319795",
    "listFilterWidget.noMatchesOutline": "#e53e3e",
    "tree.indentGuidesStroke": "#64748B",
    "activityBar.background": "#334155",
    "activityBar.dropBackground": "#334155",
    "activityBar.foreground": "#CBD5E1",
    "activityBar.border": "#475569",
    "activityBarBadge.background": "#A78BFA",
    "activityBarBadge.foreground": "#334155",
    "sideBar.background": "#293548",
    "sideBar.foreground": "#E2E8F0",
    "sideBar.border": "#0F172A",
    "sideBarTitle.foreground": "#CBD5E100",
    "sideBarSectionHeader.background": "#1E293B00",
    "sideBarSectionHeader.foreground": "#E2E8F0",
    "editorPane.background": "#334155",
    "editorGroup.emptyBackground": "#334155",
    "editorGroup.border": "#0F172A",
    "editorGroup.focusedEmptyBorder": "#475569",
    "editorGroup.dropBackground": "#4755697f",
    "editorGroupHeader.noTabsBackground": "#1E293B",
    "editorGroupHeader.tabsBackground": "#1E293B",
    "editorGroupHeader.tabsBorder": "#0F172A",
    "tab.activeBorder": "#7dd3fc",
    "tab.activeBackground": "#33415500",
    "tab.activeForeground": "#7dd3fc",
    "tab.border": "#0F172A00",
    "tab.inactiveBackground": "#1E293B",
    "tab.inactiveForeground": "#CBD5E1",
    "tab.unfocusedActiveBackground": "#1E293B",
    "tab.unfocusedActiveForeground": "#CBD5E1",
    "tab.unfocusedInactiveForeground": "#CBD5E1",
    "tab.hoverBackground": "#334155",
    "tab.unfocusedHoverBackground": "#334155",
    "editor.background": "#1E293B",
    "editor.foreground": "#E2E8F0",
    "editorLineNumber.foreground": "#64748B",
    "editorLineNumber.activeForeground": "#CBD5E1",
    "editorCursor.foreground": "#A78BFA",
    "editor.selectionBackground": "#A78BFA22",
    "editor.selectionHighlightBackground": "#334155",
    "editor.inactiveSelectionBackground": "#31979533",
    "editor.wordHighlightBackground": "#A78BFA7f",
    "editor.wordHighlightStrongBackground": "#60A5FA7f",
    "editor.findMatchBackground": "#D69E2E7f",
    "editor.findMatchHighlightBackground": "#D69E2E3f",
    "editor.findRangeHighlightBackground": "#334155",
    "editor.hoverHighlightBackground": "#334155",
    "editor.lineHighlightBackground": "#33415580",
    "editor.lineHighlightBorder": "#33415500",
    "editorLink.activeForeground": "#F472B6",
    "editor.rangeHighlightBackground": "#334155",
    "editorWhitespace.foreground": "#334155",
    "editorIndentGuide.background": "#47556980",
    "editorIndentGuide.activeBackground": "#475569",
    "editorRuler.foreground": "#334155",
    "editorCodeLens.foreground": "#4a5568",
    "editorBracketMatch.background": "#1E293B",
    "editorBracketMatch.border": "#475569",
    "editorOverviewRuler.border": "#475569",
    "editorOverviewRuler.findMatchForeground": "#D69E2Ebf",
    "editorOverviewRuler.rangeHighlightForeground": "#475569bf",
    "editorOverviewRuler.selectionHighlightForeground": "#334155bf",
    "editorOverviewRuler.wordHighlightForeground": "#475569bf",
    "editorOverviewRuler.wordHighlightStrongForeground": "#a0aec0bf",
    "editorOverviewRuler.modifiedForeground": "#60A5FA7f",
    "editorOverviewRuler.addedForeground": "#34D3997f",
    "editorOverviewRuler.deletedForeground": "#e53e3e7f",
    "editorOverviewRuler.errorForeground": "#e53e3e7f",
    "editorOverviewRuler.warningForeground": "#A78BFA7f",
    "editorOverviewRuler.infoForeground": "#3197957f",
    "editorError.foreground": "#e53e3e",
    "editorError.border": "#1E293B",
    "editorWarning.foreground": "#A78BFA",
    "editorWarning.border": "#1E293B",
    "editorGutter.background": "#1E293B",
    "editorGutter.modifiedBackground": "#60A5FA",
    "editorGutter.addedBackground": "#34D399",
    "editorGutter.deletedBackground": "#DB2777",
    "diffEditor.insertedTextBackground": "#34D39920",
    "diffEditor.removedTextBackground": "#DB277720",
    "editorWidget.background": "#334155",
    "editorWidget.border": "#475569",
    "editorSuggestWidget.background": "#334155",
    "editorSuggestWidget.border": "#475569",
    "editorSuggestWidget.foreground": "#E2E8F0",
    "editorSuggestWidget.highlightForeground": "#60A5FA",
    "editorSuggestWidget.selectedBackground": "#475569",
    "editorHoverWidget.background": "#334155",
    "editorHoverWidget.border": "#475569",
    "debugExceptionWidget.background": "#334155",
    "debugExceptionWidget.border": "#475569",
    "editorMarkerNavigation.background": "#334155",
    "editorMarkerNavigationError.background": "#e53e3e",
    "editorMarkerNavigationWarning.background": "#A78BFA",
    "peekView.border": "#60A5FA",
    "peekViewEditor.background": "#334155",
    "peekViewEditorGutter.background": "#334155",
    "peekViewEditor.matchHighlightBackground": "#D69E2E7f",
    "peekViewResult.background": "#334155",
    "peekViewResult.fileForeground": "#E2E8F0",
    "peekViewResult.lineForeground": "#475569",
    "peekViewResult.matchHighlightBackground": "#D69E2E",
    "peekViewResult.selectionBackground": "#a0aec0",
    "peekViewResult.selectionForeground": "#E2E8F0",
    "peekViewTitle.background": "#475569",
    "peekViewTitleDescription.foreground": "#4a5568",
    "peekViewTitleLabel.foreground": "#E2E8F0",
    "merge.currentHeaderBackground": "#F472B64c",
    "merge.currentContentBackground": "#F472B64c",
    "merge.incomingHeaderBackground": "#3197954c",
    "merge.incomingContentBackground": "#3197954c",
    "merge.commonContentBackground": "#A78BFA4c",
    "merge.commonHeaderBackground": "#A78BFA4c",
    "merge.border": "#718096",
    "editorOverviewRuler.currentContentForeground": "#F472B6",
    "editorOverviewRuler.incomingContentForeground": "#319795",
    "editorOverviewRuler.commonContentForeground": "#A78BFA",
    "panel.background": "#1E293B",
    "panel.border": "#0F172A",
    "panelTitle.activeBorder": "#a0aec0",
    "panelTitle.activeForeground": "#E2E8F0",
    "panelTitle.inactiveForeground": "#718096",
    "statusBar.background": "#0F172A",
    "statusBar.foreground": "#CBD5E1",
    "statusBar.border": "#0F172A00",
    "statusBar.debuggingBackground": "#0F172A",
    "statusBar.debuggingForeground": "#CBD5E1",
    "statusBar.debuggingBorder": "#A78BFA7f",
    "statusBar.noFolderBackground": "#0F172A",
    "statusBar.noFolderForeground": "#CBD5E1",
    "statusBar.noFolderBorder": "#A78BFA7f",
    "statusBarItem.activeBackground": "#F472B680",
    "statusBarItem.hoverBackground": "#34D39940",
    "statusBarItem.prominentBackground": "#F472B6",
    "statusBarItem.prominentHoverBackground": "#34D399",
    "titleBar.activeBackground": "#0F172A",
    "titleBar.activeForeground": "#E2E8F0",
    "titleBar.inactiveBackground": "#0F172A",
    "titleBar.inactiveForeground": "#64748B",
    "notification.background": "#334155",
    "notification.foreground": "#E2E8F0",
    "notification.buttonBackground": "#319795",
    "notification.buttonHoverBackground": "#F472B6",
    "notification.buttonForeground": "#334155",
    "notification.infoBackground": "#319795",
    "notification.infoForeground": "#334155",
    "notification.warningBackground": "#A78BFA",
    "notification.warningForeground": "#334155",
    "notification.errorBackground": "#e53e3e",
    "notification.errorForeground": "#334155",
    "extensionButton.prominentForeground": "#334155",
    "extensionButton.prominentBackground": "#319795",
    "extensionButton.prominentHoverBackground": "#F472B6",
    "pickerGroup.border": "#4a5568",
    "pickerGroup.foreground": "#E2E8F0",

    // Terminal
    "terminal.background": "#1E293B",
    "terminal.foreground": "#E2E8F0",
    "terminal.ansiBlack": "#000000",
    "terminal.ansiBlue": "#60A5FA",
    "terminal.ansiBrightBlack": "#4a5568",
    "terminal.ansiBrightBlue": "#4299E1",
    "terminal.ansiBrightCyan": "#38B2AC",
    "terminal.ansiBrightGreen": "#48BB78",
    "terminal.ansiBrightMagenta": "#ED64A6",
    "terminal.ansiBrightRed": "#E53E3E",
    "terminal.ansiBrightWhite": "#334155",
    "terminal.ansiBrightYellow": "#ECC94B",
    "terminal.ansiCyan": "#319795",
    "terminal.ansiGreen": "#34D399",
    "terminal.ansiMagenta": "#60A5FA",
    "terminal.ansiRed": "#C53030",
    "terminal.ansiWhite": "#334155",
    "terminal.ansiYellow": "#D69E2E",
    "terminal.selectionBackground": "#A78BFA22",
    "terminalCursor.background": "#334155",
    "terminalCursor.foreground": "#4a5568",
    "debugToolBar.background": "#334155",
    "welcomePage.buttonBackground": "#334155",
    "welcomePage.buttonHoverBackground": "#475569",
    "walkThrough.embeddedEditorBackground": "#334155",
    "gitDecoration.modifiedResourceForeground": "#93C5FD",
    "gitDecoration.deletedResourceForeground": "#DB2777",
    "gitDecoration.untrackedResourceForeground": "#C4B5FD",
    "gitDecoration.ignoredResourceForeground": "#94A3B8",
    "gitDecoration.conflictingResourceForeground": "#EF4444",
    "settings.headerForeground": "#E2E8F0",
    "settings.focusedRowBackground": "#33415540",
  },
  tokenColors: [
    {
      settings: {
        background: "#334155",
        foreground: "#E2E8F0",
        selectionBorder: "#4a5568",
        findHighlight: "#D69E2E",
        findHighlightForeground: "#334155",
        activeGuide: "#A78BFA",
        bracketsForeground: "#E2E8F07F",
        bracketsOptions: "stippled_underline",
        bracketsContentsForeground: "#E2E8F07F",
        tagsOptions: "stippled_underline",
        strings: "#7dd3fc",
      },
    },
    {
      name: "Comment",
      scope: "comment",
      settings: {
        foreground: "#94A3B8",
      },
    },
    {
      name: "Constant",
      scope: "constant",
      settings: {
        foreground: "#60A5FA",
      },
    },
    {
      name: "XML Tag",
      scope: "entity.name.tag",
      settings: {
        foreground: "#60A5FA",
      },
    },
    {
      name: "XML Attribute",
      scope: "entity.other.attribute-name",
      settings: {
        foreground: "#67e8f9",
      },
    },
    {
      name: "Entity",
      scope: "entity",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      name: "Function",
      // "scope": "entity.name.type, support.type",
      scope: "entity.name.function",
      settings: {
        foreground: "#67e8f9",
      },
    },
    {
      name: "Invalid",
      scope: "invalid",
      settings: {
        foreground: "#e53e3e",
      },
    },
    {
      name: "Keyword",
      scope: "keyword",
      settings: {
        foreground: "#A78BFA",
      },
    },
    {
      name: "Storage",
      scope: "storage",
      settings: {
        foreground: "#60A5FA",
      },
    },
    {
      name: "String",
      scope: "string",
      settings: {
        foreground: "#7dd3fc",
      },
    },
    {
      name: "Support",
      scope: "support",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      name: "Variable",
      scope: "variable",
      settings: {
        foreground: "#E2E8F0",
      },
    },
    {
      name: "Markup Heading",
      scope: "markup.heading",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      name: "Markup Deleted",
      scope: "markup.deleted",
      settings: {
        foreground: "#e53e3e",
      },
    },
    {
      name: "Markup Inserted",
      scope: "markup.inserted",
      settings: {
        foreground: "#34D399",
      },
    },
    {
      name: "Markup Changed",
      scope: "markup.changed",
      settings: {
        foreground: "#D69E2E",
      },
    },
    {
      name: "Markup Underline",
      scope: "markup.underline",
      settings: {
        fontStyle: "underline",
      },
    },
    {
      name: "Markup Underline Link",
      scope: "markup.underline.link",
      settings: {
        foreground: "#319795",
      },
    },
    {
      name: "Markup List",
      scope: "markup.list",
      settings: {
        foreground: "#E2E8F0",
      },
    },
    {
      name: "Markup Raw",
      scope: "markup.raw",
      settings: {
        foreground: "#60A5FA",
      },
    },
    {
      name: "TW HTML tags",
      scope: [
        "punctuation.definition.tag",
        "punctuation.definition.string.begin.html",
        "punctuation.definition.string.end.html",
        "punctuation.separator.key-value.html",
      ],
      settings: {
        foreground: "#63738A",
      },
    },
    {
      name: "TW CSS unit / vue",
      scope: ["keyword.other", "invalid.illegal.unrecognized-tag.html"],
      settings: {
        foreground: "#99F6E4",
      },
    },
    {
      name: "TW CSS number",
      scope: " constant.numeric.css",
      settings: {
        foreground: "#f8fafc",
      },
    },
    {
      name: "TW CSS property",
      scope: " support.type.property-name.css",
      settings: {
        foreground: "#7dd3fc",
      },
    },
    {
      name: "TW Entity",
      scope: ["entity.name.tag.template.html.vue", "entity.name.tag.html"],
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      name: "TW Vue Attributes",
      scope: "entity.other.attribute-name.html.vue",
      settings: {
        foreground: "#A78BFA",
      },
    },
    {
      name: "TW Entity HTML",
      scope: "entity.other.attribute-name.html",
      settings: {
        foreground: "#CBD5E1",
      },
    },
  ],
};
